# BASIC STATISTICS-2
Problem Statement : Hospital Patient Data Analysis
Context:  
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:  
1.	Load the patient dataset and show summary with info().  
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].  
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].  
4.	Use groupby to find total bill amount per department.  
5.	Remove duplicate patient records based on PatientID.  
6.	Fill missing BillAmount values with the mean bill amount.  
7.	Merge the billing dataset with patient dataset on PatientID.  
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).  
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).  
Expected Outcome:  
•	Final cleaned dataset with accurate billing info.  
•	All missing values handled, merged dataset across PatientID.  
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Patient_Data.csv')
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [ ]:
df.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [ ]:
df= df.drop_duplicates()

In [ ]:
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [ ]:
df['BillAmount'].fillna(df['BillAmount'].mean(), inplace=True)

/tmp/ipykernel_35075/302196808.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BillAmount'].fillna(df['BillAmount'].mean(), inplace=True)
/tmp/ipykernel_35075/302196808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BillAmount'].fillna(df['BillAmount'].mean(), inplace=True)

In [ ]:
df.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        0
ReceptionistID    0
CheckInTime       0
dtype: int64

In [ ]:
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45

In [ ]:
df1=pd.read_csv('/content/Billing_Data.csv')
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.isnull().sum()

PatientID           0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [ ]:
df2 = pd.concat([df,df1], axis=1)
df2

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,PatientID,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00,101,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30,102,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00,103,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00,104,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45,105,1000,4000

In [ ]:
df2 = pd.merge(df,df1, on='PatientID')
df2

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45,1000,4000

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   Name              5 non-null      object
 2   Department        5 non-null      object
 3   Doctor            5 non-null      object
 4   BillAmount        5 non-null      float64
 5   ReceptionistID    5 non-null      int64
 6   CheckInTime       5 non-null      object
 7   InsuranceCovered  5 non-null      int64
 8   FinalAmount       5 non-null      int64
dtypes: float64(1), int64(4), object(4)
memory usage: 492.0+ bytes

In [ ]:
df2.duplicated().sum()

np.int64(0)

In [ ]:
df2

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,1,2023-01-10 09:00,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,2,2023-01-11 10:30,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,1,2023-01-12 11:00,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3,2023-01-13 12:00,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,2,2023-01-14 08:45,1000,4000

In [ ]:
df2 = df2.drop(['ReceptionistID', 'CheckInTime'], axis=1)

In [ ]:
df2

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [ ]:
df3 = pd.DataFrame({'PatientID': [106, 107],	'Name': ['Kevin', 'Marc'],	'Department' : ['Cardiology', 'Neurology'],	'Doctor' : ['Dr. Smith', 'Dr John'],
                             'BillAmount' :  [7800.444444 , 6000.555555], 'InsuranceCovered':[4000, 5000], 'FinalAmount': [6000, 6500]})
df3

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,106,Kevin,Cardiology,Dr. Smith,7800.444444,4000,6000
1,107,Marc,Neurology,Dr John,6000.555555,5000,6500

In [ ]:
df2

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [ ]:
df4 = pd.concat([df2,df3], axis=0, ignore_index=True)
df4

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Kevin,Cardiology,Dr. Smith,7800.444444,4000,6000
6,107,Marc,Neurology,Dr John,6000.555555,5000,6500

In [ ]:
df4[['PatientID', 'Department', 'Doctor', 'BillAmount']]

   PatientID   Department     Doctor   BillAmount
0        101   Cardiology  Dr. Smith  5000.000000
1        102    Neurology   Dr. John  6233.333333
2        103  Orthopedics    Dr. Lee  7500.000000
3        104   Cardiology  Dr. Smith  6200.000000
4        105  Dermatology   Dr. Rose  6233.333333
5        106   Cardiology  Dr. Smith  7800.444444
6        107    Neurology    Dr John  6000.555555

In [ ]:
df4.groupby('Department')['BillAmount'].sum()

Department
Cardiology     19000.444444
Dermatology     6233.333333
Neurology      12233.888888
Orthopedics     7500.000000
Name: BillAmount, dtype: float64

In [ ]:
df4

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Kevin,Cardiology,Dr. Smith,7800.444444,4000,6000
6,107,Marc,Neurology,Dr John,6000.555555,5000,6500