#DATA PREPROCESSING AND FEATURE ENGINEERING IN MACHINE LEARNING
Objective:  
This assignment aims to equip you with practical skills in data preprocessing, feature engineering, and feature selection techniques, which are crucial for building efficient machine learning models. You will work with a provided dataset to apply various techniques such as scaling, encoding, and feature selection methods including isolation forest and PPS score analysis.
Dataset:    
Given "Adult" dataset, which predicts whether income exceeds $50K/yr based on census data.    
Tasks:  
1.	Handle missing values as per the best practices (imputation, removal, etc.).  
●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling  
●	Discuss the scenarios where each scaling technique is preferred and why.  
2. Encoding Techniques:  
●	Apply One-Hot Encoding to categorical variables with less than 5 categories.  
●	Use Label Encoding for categorical variables. Data Exploration and Preprocessing:  
●	Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).  
●	les with more than 5 categories.  
●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.
3. Feature Engineering:  
●	Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.  
●	Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [ ]:
# import all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/adult_with_headers (1).csv')
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
#EDA
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
df.isin([' ?']).sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [ ]:
df.replace(' ?', np.nan, inplace=True)

In [ ]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(23)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info() # to see what is my numerical data and categorical data
# 1.	Handle missing values as per the best practices (imputation, removal, etc.).

<class 'pandas.core.frame.DataFrame'>
Index: 30139 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30139 non-null  int64
 1   workclass       30139 non-null  object
 2   fnlwgt          30139 non-null  int64
 3   education       30139 non-null  object
 4   education_num   30139 non-null  int64
 5   marital_status  30139 non-null  object
 6   occupation      30139 non-null  object
 7   relationship    30139 non-null  object
 8   race            30139 non-null  object
 9   sex             30139 non-null  object
 10  capital_gain    30139 non-null  int64
 11  capital_loss    30139 non-null  int64
 12  hours_per_week  30139 non-null  int64
 13  native_country  30139 non-null  object
 14  income          30139 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [ ]:
x_num=df.iloc[:,10:13] #df.iloc is integerbased indexing
x_num

       capital_gain  capital_loss  hours_per_week
0              2174             0              40
1                 0             0              13
2                 0             0              40
3                 0             0              40
4                 0             0              40
...             ...           ...             ...
32556             0             0              38
32557             0             0              40
32558             0             0              40
32559             0             0              20
32560         15024             0              40

[30139 rows x 3 columns]

In [ ]:
x_num=df[['age','fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week'] ]
x_num

       age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week
0       39   77516             13          2174             0              40
1       50   83311             13             0             0              13
2       38  215646              9             0             0              40
3       53  234721              7             0             0              40
4       28  338409             13             0             0              40
...    ...     ...            ...           ...           ...             ...
32556   27  257302             12             0             0              38
32557   40  154374              9             0             0              40
32558   58  151910              9             0             0              40
32559   22  201490              9             0             0              20
32560   52  287927              9         15024             0              40

[30139 rows x 6 columns]

In [ ]:
#standardisation
from sklearn.preprocessing import StandardScaler  #standard scalar is class and object
sc = StandardScaler()
x_sc=sc.fit_transform(x_num) #till this step we get result in array
x_sc=pd.DataFrame(x_sc) #hence dataframe is used for rows and columns
x_sc.columns=list(x_num) #this gives the header names
x_sc

#here the values are between -3 to +3  Preferred for: Algorithms assuming normal distribution algorithms use distance outliers are acceptable for SVM, Logistic Regression, PCA

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.042516,-1.062676,1.128996,0.145925,-0.218673,-0.078031
1,0.880215,-1.007829,1.128996,-0.147502,-0.218673,-2.332060
2,-0.033639,0.244669,-0.440434,-0.147502,-0.218673,-0.078031
3,1.108678,0.425206,-1.225149,-0.147502,-0.218673,-0.078031
4,-0.795183,1.406572,1.128996,-0.147502,-0.218673,-0.078031
...,...,...,...,...,...,...
30134,-0.871338,0.638926,0.736639,-0.147502,-0.218673,-0.244996
30135,0.118670,-0.335246,-0.440434,-0.147502,-0.218673,-0.078031
30136,1.489450,-0.358567,-0.440434,-0.147502,-0.218673,-0.078031
30137,-1.252110,0.110688,-0.440434,-0.147502,-0.218673,-1.747682
30138,1.032523,0.928780,-0.440434,1.880305,-0.218673,-0.078031

In [ ]:
#normalisation/scaling
from sklearn.preprocessing import MinMaxScaler
mm= MinMaxScaler()
mm.fit_transform(x_num)
x_mm=pd.DataFrame(mm.fit_transform(x_num))
x_mm.columns =list(x_num)
x_mm
#values here are between 0 to 1
#we can use either one of either minmax scalar or standardisation. - Preferred for: Neural networks, When preserving relative distances is important, When no assumption of normality

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.043338,0.800000,0.021740,0.0,0.397959
1,0.452055,0.047277,0.800000,0.000000,0.0,0.122449
2,0.287671,0.137244,0.533333,0.000000,0.0,0.397959
3,0.493151,0.150212,0.400000,0.000000,0.0,0.397959
4,0.150685,0.220703,0.800000,0.000000,0.0,0.397959
...,...,...,...,...,...,...
30134,0.136986,0.165563,0.733333,0.000000,0.0,0.377551
30135,0.315068,0.095589,0.533333,0.000000,0.0,0.397959
30136,0.561644,0.093914,0.533333,0.000000,0.0,0.397959
30137,0.068493,0.127620,0.533333,0.000000,0.0,0.193878
30138,0.479452,0.186383,0.533333,0.150242,0.0,0.397959

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30139 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30139 non-null  int64
 1   workclass       30139 non-null  object
 2   fnlwgt          30139 non-null  int64
 3   education       30139 non-null  object
 4   education_num   30139 non-null  int64
 5   marital_status  30139 non-null  object
 6   occupation      30139 non-null  object
 7   relationship    30139 non-null  object
 8   race            30139 non-null  object
 9   sex             30139 non-null  object
 10  capital_gain    30139 non-null  int64
 11  capital_loss    30139 non-null  int64
 12  hours_per_week  30139 non-null  int64
 13  native_country  30139 non-null  object
 14  income          30139 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
#to convert categorical variable into numerical we use label and one hot encoder
x_cat=df[['workclass','education','marital_status','occupation','relationship','race','sex','native_country','income']]
x_cat
#we have to assign each column to each variable and thenc concat which is a huge time consuimg hence we use df

,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,>50K

In [ ]:
#labelencoder
from sklearn.preprocessing import LabelEncoder  #standard scalar is class and object
le = LabelEncoder()
le.fit_transform(x_cat)
#fit transform only takes ONED array when you take categorical variable so we take another

ValueError: y should be a 1d array, got an array of shape (30139, 9) instead.

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x_cat['workclass']=le.fit_transform(x_cat['workclass'])
x_cat['education']=le.fit_transform(x_cat['education'])
x_cat['occupation']=le.fit_transform(x_cat['occupation'])
x_cat['native_country']=le.fit_transform(x_cat['native_country'])
x_cat

/tmp/ipykernel_1839/155267442.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_cat['workclass']=le.fit_transform(x_cat['workclass'])
/tmp/ipykernel_1839/155267442.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_cat['education']=le.fit_transform(x_cat['education'])
/tmp/ipykernel_1839/155267442.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_cat['occupation']=le.fit_transform(x_cat['occupation'])
/tmp/ipykernel_1839/155267442.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_cat['native_country']=le.fit_transform(x_cat['native_country'])

,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
0,5,9,4,0,1,4,1,38,0
1,4,9,2,3,0,4,1,38,0
2,2,11,0,5,1,4,1,38,0
3,2,1,2,5,0,2,1,38,0
4,2,9,2,9,5,2,0,4,0
...,...,...,...,...,...,...,...,...,...
32556,2,7,2,12,5,4,0,38,0
32557,2,11,2,6,0,4,1,38,1
32558,2,11,6,0,4,4,0,38,0
32559,2,11,4,0,3,4,1,38,0
32560,3,11,2,3,5,4,0,38,1

In [ ]:
#one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit_transform(x_cat).toarray()#this doesnt give array so we convert it into array
#here we dont know from where its assigning

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
#one hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
oh2=ohe.fit_transform(x_cat[['sex']]).toarray()
oh2=pd.DataFrame(oh2)
oh2.columns = ['Male', 'Female']
oh2

       Male  Female
0       0.0     1.0
1       0.0     1.0
2       0.0     1.0
3       0.0     1.0
4       1.0     0.0
...     ...     ...
30134   1.0     0.0
30135   0.0     1.0
30136   1.0     0.0
30137   0.0     1.0
30138   1.0     0.0

[30139 rows x 2 columns]


# One-Hot Encoding:
if there are three variables in a column it creates threee columns and gives bimary metrix(1 and 0)
Advantages
Does not create ordinal relationship.
Works well for nominal categorical data.
Disadvantages
Increases dimensionality.
Can create sparse datasets.
#Label Encoding:
based on alphabetical order gives interger to each of the values present in the column
Advantages
Simple and memory efficient.
Useful for tree-based models.
Disadvantages
Introduces ordinal relationship.
May affect performance in linear models.

In [ ]:
df['capital_diff'] = df['capital_gain'] - df['capital_loss']
df['capital_diff']

0         2174
1            0
2            0
3            0
4            0
         ...
32556        0
32557        0
32558        0
32559        0
32560    15024
Name: capital_diff, Length: 30139, dtype: int64

In [ ]:
df['hours_per_age'] = df['hours_per_week'] / df['age']
df['hours_per_age']
#capital_diff captures overall financial status.
#hours_per_age measures work intensity relative to age.

0        1.025641
1        0.260000
2        1.052632
3        0.754717
4        1.428571
           ...
32556    1.407407
32557    1.000000
32558    0.689655
32559    0.909091
32560    0.769231
Name: hours_per_age, Length: 30139, dtype: float64

In [ ]:
df['log_capital_gain'] = np.log1p(df['capital_gain'])
#Log transformation reduces skewness and helps machine learning algorithms perform better by making the distribution more normal.