#Recommendation System
recommendation is done for right descision.
process of suggesting some relevant items to users based on their preferences, behaviours, or past activities its commonly used in domains like: e commerce, streaming services, social media, news platforms.

suggesting based on preferences or etc for right deciscion. this is also a part of unsupervised learning.

why recommendation sis important
. personalized experience: trailors suggestions to individual users, increasing engagement and satisfaction
increase sales and usage:  drives more clicks purchases or watch time
efficient discovery: helps users find relevant content faster
user retention: personalized content keeps users coming back
competitive edge : high quality recommendation can set a business apart


how does it work?
general steps:
collect data
pre processing
modeling
prediction
evaluvation


there are two types of recommendation system
1. content based : only related to user.  it is a recommendation technique that suggests items to users based on the charachterestics or attributes of the items they have previously interacted with or show interest in

2. collaborative system : we are just comparing likeness and dislike of two persons. if a person A has the same opition as person B on an issue, A is more likely to have B s opinion on a differetn issue x, when compared to the opinion of a person chosen randomly


calculate similarity between user profile and item profile we have many techniques but we concentrate on cosine similaRITY
1. cosine similarity
2. wuclidean distance
3. dot product
4. jaccard similarity

1. cosine similarity: cos(a,b)= a.b/|a|*|b|
cosine similarity measures how similar two vectors are, based on the cosine of the angle between them. Ranges from 0 to 1
higher value=more similar
cosine distance: is cosine distance=1-cosine similarity
ranges from 0(same direction) to 1(opposite)

from sklearn.metrics import pairwise_distance

#Assignment
Recommendation System  
  
Data Description:
  
Unique ID of each anime.  
Anime title.  
Anime broadcast type, such as TV, OVA, etc.  
anime genre.  
The number of episodes of each anime.  
The average rating for each anime compared to the number of users who gave ratings.  
  
  
Number of community members for each anime.  
Objective:  
The objective of this assignment is to implement a recommendation system using cosine similarity on an anime dataset.  
Dataset:  
Use the Anime Dataset which contains information about various anime, including their titles, genres,No.of episodes and user ratings etc.  
  
Tasks:  

Data Preprocessing:  

Load the dataset into a suitable data structure (e.g., pandas DataFrame).
Handle missing values, if any.  
Explore the dataset to understand its structure and attributes.
  
Feature Extraction:  
  
Decide on the features that will be used for computing similarity (e.g., genres, user ratings).  
Convert categorical features into numerical representations if necessary.
Normalize numerical features if required.  
  
Recommendation System:   
  
Design a function to recommend anime based on cosine similarity.  
Given a target anime, recommend a list of similar anime based on cosine similarity scores.  
Experiment with different threshold values for similarity scores to adjust the recommendation list size.  
Analyze the performance of  the recommendation system and identify areas of improvement.  

Interview Questions:  
1. Can you explain the difference between user-based and item-based collaborative filtering?  
2. What is collaborative filtering, and how does it work?

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df=pd.read_csv('/content/anime.csv')
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [ ]:
df.shape

(12294, 7)

In [ ]:
df.size

86058

In [ ]:
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [ ]:
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [ ]:
df.tail()

,anime_id,name,genre,type,episodes,rating,members
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [ ]:
df.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [ ]:
df['genre']=df['genre'].fillna('unknown')
df['type']=df['type'].fillna('unknown')
df['rating']=df['rating'].fillna(df['rating'].mean())

In [ ]:
df.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [ ]:
df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [ ]:
df["anime_id"].unique()

array([32281,  5114, 28977, ...,  5621,  6133, 26081])

In [ ]:
len(df["anime_id"].unique())

12294

In [ ]:
df["genre"].value_counts()

genre
Hentai                                                        823
Comedy                                                        523
Music                                                         301
Kids                                                          199
Comedy, Slice of Life                                         179
                                                             ...
Adventure, Fantasy, Historical, Martial Arts, Supernatural      1
School, Slice of Life, Supernatural                             1
Comedy, Mecha, Police, Sci-Fi, Shounen                          1
Comedy, Parody, School, Shounen                                 1
Action, Comedy, Drama, Mecha, Music, Sci-Fi, Shounen            1
Name: count, Length: 3265, dtype: int64

In [ ]:
len(df["genre"].value_counts())

3265

In [ ]:
df["type"].value_counts()

type
TV         3787
OVA        3311
Movie      2348
Special    1676
ONA         659
Music       488
unknown      25
Name: count, dtype: int64

In [ ]:
len(df["type"].value_counts())

7

In [ ]:
df["name"].value_counts()

name
Saru Kani Gassen                                     2
Shi Wan Ge Leng Xiaohua                              2
Bary-san x Gospe Rats: Tonde Bary Bary Monogatari    1
Ba La La Xiao Mo Xian Zhi: Qiji Wubu                 1
Backkom Meogeujan Yeohaeng                           1
                                                    ..
3-gatsu no Lion meets Bump of Chicken                1
Bannou Bunka Neko-Musume                             1
Choujikuu Seiki Orguss                               1
Chuuzumou                                            1
Star Driver the Movie                                1
Name: count, Length: 12292, dtype: int64

In [ ]:
features = df[['genre','rating','members']]
features.head()

                                               genre  rating  members
0               Drama, Romance, School, Supernatural    9.37   200630
1  Action, Adventure, Drama, Fantasy, Magic, Mili...    9.26   793665
2  Action, Comedy, Historical, Parody, Samurai, S...    9.25   114262
3                                   Sci-Fi, Thriller    9.17   673572
4  Action, Comedy, Historical, Parody, Samurai, S...    9.16   151266

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')

genre_matrix = tfidf.fit_transform(df['genre'])

In [ ]:
scaler = MinMaxScaler()

numerical_features = scaler.fit_transform(
    df[['rating','members']]
)

In [ ]:
from scipy.sparse import hstack

combined_features = hstack([
    genre_matrix,
    numerical_features
])

In [ ]:
cosine_sim = cosine_similarity(combined_features)

print(cosine_sim.shape)

(12294, 12294)

In [ ]:
indices = pd.Series(df.index,
                    index=df['name']).drop_duplicates()

In [ ]:
def recommend_anime(title, top_n=10):

    if title not in indices:
        return "Anime not found."

    idx = indices[title]

    similarity_scores = list(
        enumerate(cosine_sim[idx])
    )

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    similarity_scores = similarity_scores[1:top_n+1]

    anime_indices = [i[0] for i in similarity_scores]

    recommendations = df[['name','genre','rating']].iloc[
        anime_indices
    ].copy()

    recommendations['Similarity Score'] = [
        i[1] for i in similarity_scores
    ]

    return recommendations

In [ ]:
recommend_anime("Naruto")
recommend_anime("Death Note")
recommend_anime("One Piece")

,name,genre,rating,Similarity Score
241,One Piece: Episode of Nami - Koukaishi no Nami...,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",8.270000,0.940203
86,Shingeki no Kyojin,"Action, Drama, Fantasy, Shounen, Super Power",8.540000,0.939357
231,One Piece: Episode of Merry - Mou Hitori no Na...,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",8.290000,0.938252
896,One Piece: Episode of Sabo - 3 Kyoudai no Kizu...,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",7.780000,0.935466
6,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",9.130000,0.930366
717,Shingeki no Kyojin OVA,"Action, Drama, Fantasy, Shounen, Super Power",7.880000,0.920145
10899,Shingeki no Kyojin Season 2,"Action, Drama, Fantasy, Shounen, Super Power",6.473902,0.916939
352,One Piece Film: Strong World Episode 0,"Action, Adventure, Comedy, Fantasy, Shounen, S...",8.160000,0.912709
941,One Piece Movie 4: Dead End no Bouken,"Action, Adventure, Comedy, Fantasy, Shounen, S...",7.760000,0.912513
2492,One Piece Movie 1,"Action, Adventure, Comedy, Fantasy, Shounen, S...",7.250000,0.910536

In [ ]:
def recommend_with_threshold(title, threshold=0.5):

    idx = indices[title]

    sim_scores = list(
        enumerate(cosine_sim[idx])
    )

    filtered = [
        score for score in sim_scores
        if score[1] > threshold
    ]

    filtered = sorted(
        filtered,
        key=lambda x:x[1],
        reverse=True
    )

    anime_idx = [i[0] for i in filtered[1:]]

    return df['name'].iloc[anime_idx]

In [ ]:
recommend_with_threshold("Naruto",0.5)

615                                    Naruto: Shippuuden
206                                         Dragon Ball Z
346                                           Dragon Ball
1472          Naruto: Shippuuden Movie 4 - The Lost Tower
1573    Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...
                              ...
431             Prince of Tennis: The National Tournament
3173                           Lupin III: Kiri no Elusive
4434                               Battle Spirits: Heroes
3256    Lupin III: Ai no Da Capo - Fujiko&#039;s Unluc...
482                                      Prince of Tennis
Name: name, Length: 752, dtype: object

In [ ]:
recommend_with_threshold("Naruto",0.7)

615                                     Naruto: Shippuuden
206                                          Dragon Ball Z
346                                            Dragon Ball
1472           Naruto: Shippuuden Movie 4 - The Lost Tower
1573     Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...
                               ...
1706                  Grappler Baki: Saidai Tournament-hen
1498                                              Kure-nai
740                                Toaru Kagaku no Railgun
10493                           Tatakae!! Ramenman (Movie)
1333                    Bleach Movie 1: Memories of Nobody
Name: name, Length: 137, dtype: object

In [ ]:
recommend_with_threshold("Naruto",0.9)

615                                    Naruto: Shippuuden
206                                         Dragon Ball Z
346                                           Dragon Ball
1472          Naruto: Shippuuden Movie 4 - The Lost Tower
1573    Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...
486                              Boruto: Naruto the Movie
Name: name, dtype: object

Lower threshold gives more recommendations.  
Higher threshold gives fewer but more relevant recommendations.  
Threshold 0.7 generally balances quality and quantity.  

Simple to implement.  
Measures similarity regardless of vector size.  
Works efficiently with sparse TF-IDF matrices.  
Provides relevant recommendations based on content.  
Additional Notes:
The recommendation system successfully identifies similar anime using cosine similarity.
Genre contributes most to similarity, while rating and member count improve ranking.
A threshold of 0.7 gives more relevant recommendations than 0.5.
Very high thresholds (0.9) return only a few recommendations.

Difference Between User-Based and Item-Based Collaborative Filtering  
**User-Based Collaborative Filtering: ** Finds users with similar preferences.
Recommends items liked by similar users.  
Example:
If User A and User B like the same anime, anime watched by User B can be recommended to User A.  

**Item-Based Collaborative Filtering **:  Finds items similar to each other.
Recommends items similar to previously liked items.
Example:
If a user likes Naruto, the system recommends anime similar to Naruto.

Comparison
User-Based	Item-Based
User similarity	Item similarity
Dynamic	More stable
Slower for large datasets	Faster for large datasets
Less scalable	More scalable

2. What is Collaborative Filtering?

Collaborative Filtering is a recommendation technique that predicts user preferences based on the behavior of similar users or similar items.

Working Process
Collect user-item interactions.
Measure similarity.
Identify neighbors.
Generate recommendations.
Types
User-Based Collaborative Filtering
Item-Based Collaborative Filtering
Advantages
Personalized recommendations.
No need for item content.
Disadvantages
Cold-start problem.
Data sparsity.
Scalability issues.